Created roots_of_quadratic.py
GiovanniBruno22/PythonBeginners pull request #14
Opened 2023-07-29 12:42 UTC by githubsharat

Wrote a python code that finds out roots of a quadratic equation. I am learning open source contribution. Please give me any feedback if possible. Thank you.

2023-07-30 10:14 UTC, GiovanniBruno22 requested changes

2023-07-30 10:14 UTC, GiovanniBruno22 commented on scripts/roots_of_quadratic.py
> +#roots of quadratic equation in the form of ax^2 + bx + c = 0
Trivial: Could you move this comment inside the function and add it as a docstring instead?

2023-07-30 10:14 UTC, GiovanniBruno22 commented on scripts/roots_of_quadratic.py
> +a,b,c = input("Enter the values of a, b, and c (seperated by commas) for the equation ax^2 + bx + c = 0 : ").split(',')
Could you move line 7 and 8 inside a main function and call it using:
```
if __name__ == '__main__':
        main()
```
To stay consistent with the rest of the scripts in the repo?

Everything else looks good to me!

2023-07-30 22:07 UTC, githubsharat commented
I am sorry I did not perform the changes yet. I am new to GitHub. I will correct my code soon.

2023-07-30 22:27 UTC, githubsharat commented
I just made the commit: f429348acee8bceede5ec760e17045ebfda8f9e3

Included all the suggested changes. I am sorry again about the earlier accidental resolve.

Thank you very much!

2023-07-31 08:38 UTC, GiovanniBruno22 approved these changes
This looks good to me! thank you so much for your contribution @githubsharat !

2023-07-31 08:38 UTC, GiovanniBruno22 commented
Merging this in!

2023-07-31 08:38 UTC, merged

2023-08-01 09:42 UTC, githubsharat commented
> This looks good to me! thank you so much for your contribution @githubsharat !

Thank you for your feedback and opportunity to learn open-source contribution! @GiovanniBruno22